<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepositoryUoW.Core\RepositoryUoW.Core.csproj" />
    <ProjectReference Include="..\RepositoryUoW.Domain\RepositoryUoW.Domain.csproj" />
    <ProjectReference Include="..\RepositoryUoW.Infrastructure.SQL\RepositoryUoW.Infrastructure.SQL.csproj" />
    <ProjectReference Include="..\RepositoryUoW.Infrastructure.MongoDB\RepositoryUoW.Infrastructure.MongoDB.csproj" />
  </ItemGroup>

</Project>
